### PR TITLE
Add Universal Devices PlugIn

### PR DESCRIPTION
**Pull request by Mazecreator**
Add Universal Devices

### CODE REVIEW

**Comment by BarRaider** [comment]
Please remove the UUIDs to other plugins (line 124)

**Comment by Mazecreator** [comment]
@BarRaider I don't understand your request....

**Comment by BarRaider** [comment]
https://github.com/Mazecreator/udcontrol-streamdeck/blob/fe577c262d5c53a555cd7349e5e32da0202b5905/Sources/com.mazecreator.udcontrol.sdPlugin/code.html#L124

**Comment by BarRaider** [comment]
Sorry for the delay. Merged.

**Pull request merged**
